name: Build Stack-chan Firmware
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: ./.github/actions/setup
      - name: Check Format
        run: npm run format
        working-directory: ./firmware
      - name: Lint
        run: npm run lint
        working-directory: ./firmware
      - name: Build
        run: source $HOME/.local/share/xs-dev-export.sh && npm run build
        working-directory: ./firmware
      - name: Build CoreS3
        run: source $HOME/.local/share/xs-dev-export.sh && npm run build --target=esp32/m5stack_cores3
        working-directory: ./firmware
